---
:root: /opt/crossfader/versions
:root_is_prefix: false
:name: crossfader
:name_suffix: ruby_187p371
:ruby:
  :src: src/ruby-1.8.7-p371
  :version: 1.8.7-p371
:openssl:
  :src: src/openssl-1.0.1p
:zlib:
  :src: src/zlib-1.2.7
:yaml:
  :src: src/yaml-0.1.6
:ffi:
  :src: src/libffi-3.0.11
:autoconf:
  :src: src/autoconf-2.68
:rubygems:
  :src: src/rubygems-1.8.24
